name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  draft_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    outputs:
      tag_name: ${{ steps.release-drafter.outputs.tag_name }}
    steps:
      # Get next version
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      # Comment out to enable these permissions if needed.
      # packages: write
      # deployments: write
      # id-token: write
    if: github.event_name == 'workflow_dispatch'
    needs: draft_release
    steps:
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
